# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlg.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tnlg.proto\x12\x0bmt_nlp_demo\"\x88\x01\n\nNLGMessage\x12\x12\n\nchannel_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x03(\t\x12\x15\n\rprompt_prefix\x18\x03 \x01(\t\x12\x15\n\rprompt_suffix\x18\x04 \x01(\t\x12\x19\n\x11max_output_length\x18\x05 \x01(\x05\x12\x0c\n\x04\x61rgs\x18\x06 \x03(\t\"-\n\x0bNLGResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x0e\n\x06others\x18\x03 \x03(\t2M\n\nNLGService\x12?\n\x06NLGGet\x12\x17.mt_nlp_demo.NLGMessage\x1a\x18.mt_nlp_demo.NLGResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nlg_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NLGMESSAGE._serialized_start=27
  _NLGMESSAGE._serialized_end=163
  _NLGRESPONSE._serialized_start=165
  _NLGRESPONSE._serialized_end=210
  _NLGSERVICE._serialized_start=212
  _NLGSERVICE._serialized_end=289
# @@protoc_insertion_point(module_scope)
