# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dm_stream.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x64m_stream.proto\x12\x06nlp.dm\"h\n\x0eHistoryElement\x12\x14\n\x0c\x63onversation\x18\x01 \x03(\t\x12\x0e\n\x06intent\x18\x02 \x03(\t\x12\r\n\x05slots\x18\x03 \x03(\t\x12\x10\n\x08\x65ntities\x18\x04 \x03(\t\x12\x0f\n\x07task_id\x18\x05 \x03(\x03\"B\n\tDmRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\'\n\x07history\x18\x02 \x01(\x0b\x32\x16.nlp.dm.HistoryElement\"\x1c\n\nDmResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t26\n\x02\x44m\x12\x30\n\x05GetDm\x12\x11.nlp.dm.DmRequest\x1a\x12.nlp.dm.DmResponse0\x01\x42\x1f\n\x1d\x63om.mthreads.ai.protos.nlp.dmb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dm_stream_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.mthreads.ai.protos.nlp.dm'
  _HISTORYELEMENT._serialized_start=27
  _HISTORYELEMENT._serialized_end=131
  _DMREQUEST._serialized_start=133
  _DMREQUEST._serialized_end=199
  _DMRESPONSE._serialized_start=201
  _DMRESPONSE._serialized_end=229
  _DM._serialized_start=231
  _DM._serialized_end=285
# @@protoc_insertion_point(module_scope)
