# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nlg.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tnlg.proto\x12\x0bmt_nlp_demo\"Z\n\nNLGMessage\x12\x12\n\nchannel_id\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x02 \x03(\t\x12\x19\n\x11max_output_length\x18\x03 \x01(\x05\x12\x0c\n\x04\x61rgs\x18\x04 \x03(\t\"-\n\x0bNLGResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\x12\x0e\n\x06others\x18\x03 \x03(\t2D\n\x03NLG\x12=\n\x06NLGGet\x12\x17.mt_nlp_demo.NLGMessage\x1a\x18.mt_nlp_demo.NLGResponse\"\x00\x62\x06proto3')



_NLGMESSAGE = DESCRIPTOR.message_types_by_name['NLGMessage']
_NLGRESPONSE = DESCRIPTOR.message_types_by_name['NLGResponse']
NLGMessage = _reflection.GeneratedProtocolMessageType('NLGMessage', (_message.Message,), {
  'DESCRIPTOR' : _NLGMESSAGE,
  '__module__' : 'nlg_pb2'
  # @@protoc_insertion_point(class_scope:mt_nlp_demo.NLGMessage)
  })
_sym_db.RegisterMessage(NLGMessage)

NLGResponse = _reflection.GeneratedProtocolMessageType('NLGResponse', (_message.Message,), {
  'DESCRIPTOR' : _NLGRESPONSE,
  '__module__' : 'nlg_pb2'
  # @@protoc_insertion_point(class_scope:mt_nlp_demo.NLGResponse)
  })
_sym_db.RegisterMessage(NLGResponse)

_NLG = DESCRIPTOR.services_by_name['NLG']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NLGMESSAGE._serialized_start=26
  _NLGMESSAGE._serialized_end=116
  _NLGRESPONSE._serialized_start=118
  _NLGRESPONSE._serialized_end=163
  _NLG._serialized_start=165
  _NLG._serialized_end=233
# @@protoc_insertion_point(module_scope)
