# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import nlg_pb2 as nlg__pb2


class NLGStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.NLGGet = channel.unary_unary(
                '/mt_nlp_demo.NLG/NLGGet',
                request_serializer=nlg__pb2.NLGMessage.SerializeToString,
                response_deserializer=nlg__pb2.NLGResponse.FromString,
                )


class NLGServicer(object):
    """Missing associated documentation comment in .proto file."""

    def NLGGet(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NLGServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'NLGGet': grpc.unary_unary_rpc_method_handler(
                    servicer.NLGGet,
                    request_deserializer=nlg__pb2.NLGMessage.FromString,
                    response_serializer=nlg__pb2.NLGResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'mt_nlp_demo.NLG', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class NLG(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def NLGGet(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/mt_nlp_demo.NLG/NLGGet',
            nlg__pb2.NLGMessage.SerializeToString,
            nlg__pb2.NLGResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
