# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dm.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x08\x64m.proto\x12\x06nlp.dm\"P\n\tDmRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0f\n\x07history\x18\x02 \x03(\t\x12\x12\n\nsession_id\x18\x03 \x01(\x03\x12\x10\n\x08robot_id\x18\x04 \x01(\x03\"\x1a\n\nDmResponse\x12\x0c\n\x04text\x18\x01 \x01(\t24\n\x02\x44m\x12.\n\x05GetDm\x12\x11.nlp.dm.DmRequest\x1a\x12.nlp.dm.DmResponseB\x1f\n\x1d\x63om.mthreads.ai.protos.nlp.dmb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dm_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\035com.mthreads.ai.protos.nlp.dm'
  _DMREQUEST._serialized_start=20
  _DMREQUEST._serialized_end=100
  _DMRESPONSE._serialized_start=102
  _DMRESPONSE._serialized_end=128
  _DM._serialized_start=130
  _DM._serialized_end=182
# @@protoc_insertion_point(module_scope)
